// <auto-generated />
using System;
using DAL_DataAccessLayer.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL_DataAccessLayer.Migrations
{
    [DbContext(typeof(QuanLiTourDbContext))]
    [Migration("20211112200552_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiPhi", b =>
                {
                    b.Property<int>("maChiPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<int>("maLoaiCP")
                        .HasColumnType("int");

                    b.Property<decimal>("soTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maChiPhi");

                    b.HasIndex("maDoan");

                    b.HasIndex("maLoaiCP");

                    b.ToTable("ChiPhis");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiTiet", b =>
                {
                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<int>("maKh")
                        .HasColumnType("int");

                    b.HasKey("maDoan", "maKh");

                    b.HasIndex("maKh");

                    b.ToTable("ChiTiets");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.DiaDiem", b =>
                {
                    b.Property<int>("maDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenDiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maDiaDiem");

                    b.ToTable("DiaDiems");

                    b.HasData(
                        new
                        {
                            maDiaDiem = 1,
                            tenDiaDiem = "Địa Điểm 1"
                        },
                        new
                        {
                            maDiaDiem = 2,
                            tenDiaDiem = "Địa Điểm 2"
                        },
                        new
                        {
                            maDiaDiem = 3,
                            tenDiaDiem = "Địa Điểm 3"
                        },
                        new
                        {
                            maDiaDiem = 4,
                            tenDiaDiem = "Địa Điểm 4"
                        },
                        new
                        {
                            maDiaDiem = 5,
                            tenDiaDiem = "Địa Điểm 5"
                        },
                        new
                        {
                            maDiaDiem = 6,
                            tenDiaDiem = "Địa Điểm 6"
                        });
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Doan", b =>
                {
                    b.Property<int>("maDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("doanhThu")
                        .HasColumnType("real");

                    b.Property<int>("maTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.HasKey("maDoan");

                    b.HasIndex("maTour");

                    b.ToTable("Doans");

                    b.HasData(
                        new
                        {
                            maDoan = 1,
                            doanhThu = 0f,
                            maTour = 4,
                            ngayKetThuc = new DateTime(2021, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayKhoiHanh = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            maDoan = 2,
                            doanhThu = 0f,
                            maTour = 1,
                            ngayKetThuc = new DateTime(2021, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayKhoiHanh = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            maDoan = 3,
                            doanhThu = 0f,
                            maTour = 2,
                            ngayKetThuc = new DateTime(2021, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayKhoiHanh = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            maDoan = 4,
                            doanhThu = 0f,
                            maTour = 3,
                            ngayKetThuc = new DateTime(2021, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngayKhoiHanh = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.GiaTour", b =>
                {
                    b.Property<int>("maGiaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("maTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("thanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maGiaTour");

                    b.HasIndex("maTour");

                    b.ToTable("GiaTours");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Khach", b =>
                {
                    b.Property<int>("maKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cnmd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenKh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maKh");

                    b.ToTable("Khachs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiChiPhi", b =>
                {
                    b.Property<int>("maLoaiCP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenLoaiCP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maLoaiCP");

                    b.ToTable("LoaiChiPhis");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiHinhDuLich", b =>
                {
                    b.Property<int>("maLoaiHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenLoaiHinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maLoaiHinh");

                    b.ToTable("LoaiHinhDuLichs");

                    b.HasData(
                        new
                        {
                            maLoaiHinh = 1,
                            tenLoaiHinh = "Du lịch tham quan"
                        },
                        new
                        {
                            maLoaiHinh = 2,
                            tenLoaiHinh = "Du lịch văn hóa"
                        },
                        new
                        {
                            maLoaiHinh = 3,
                            tenLoaiHinh = "Du lịch ẩm thực"
                        },
                        new
                        {
                            maLoaiHinh = 4,
                            tenLoaiHinh = "Du lịch xanh"
                        });
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.NhanVien", b =>
                {
                    b.Property<int>("maNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenNv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maNv");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.PhanBo", b =>
                {
                    b.Property<int>("maNv")
                        .HasColumnType("int");

                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<string>("nhiemVu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maNv", "maDoan");

                    b.HasIndex("maDoan");

                    b.ToTable("PhanBos");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ThamQuan", b =>
                {
                    b.Property<int>("maDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("maTour")
                        .HasColumnType("int");

                    b.Property<int>("thuTuThamQuan")
                        .HasColumnType("int");

                    b.HasKey("maDiaDiem", "maTour");

                    b.HasIndex("maTour");

                    b.ToTable("ThamQuans");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Tour", b =>
                {
                    b.Property<int>("maTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("dacDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("khachSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maLoaiHinh")
                        .HasColumnType("int");

                    b.Property<string>("noiDungTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maTour");

                    b.HasIndex("maLoaiHinh");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            maTour = 1,
                            dacDiem = "Đặc điểm 1",
                            khachSan = "Khách Sạn 1",
                            maLoaiHinh = 1,
                            noiDungTour = "Nội dung tour",
                            tenTour = "Tên Tour 1",
                            trangThai = false
                        },
                        new
                        {
                            maTour = 2,
                            dacDiem = "Đặc điểm 1",
                            khachSan = "Khách Sạn 2",
                            maLoaiHinh = 2,
                            noiDungTour = "Nội dung tour",
                            tenTour = "Tên Tour 2",
                            trangThai = false
                        },
                        new
                        {
                            maTour = 3,
                            dacDiem = "Đặc điểm 3",
                            khachSan = "Khách Sạn 3",
                            maLoaiHinh = 2,
                            noiDungTour = "Nội dung tour",
                            tenTour = "Tên Tour 3",
                            trangThai = false
                        },
                        new
                        {
                            maTour = 4,
                            dacDiem = "Đặc điểm 1",
                            khachSan = "Khách Sạn 2",
                            maLoaiHinh = 2,
                            noiDungTour = "Nội dung tour",
                            tenTour = "Tên Tour 2",
                            trangThai = false
                        });
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiPhi", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("ChiPhis")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.LoaiChiPhi", "LoaiChiPhi")
                        .WithMany("ChiPhis")
                        .HasForeignKey("maLoaiCP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("LoaiChiPhi");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiTiet", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("ChiTiets")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.Khach", "Khach")
                        .WithMany("ChiTiets")
                        .HasForeignKey("maKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("Khach");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Doan", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Tour", "Tour")
                        .WithMany("Doans")
                        .HasForeignKey("maTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.GiaTour", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Tour", "Tour")
                        .WithMany("GiaTours")
                        .HasForeignKey("maTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.PhanBo", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("PhanBos")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.NhanVien", "NhanVien")
                        .WithMany("PhanBos")
                        .HasForeignKey("maNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ThamQuan", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.DiaDiem", "DiaDiem")
                        .WithMany("ThamQuans")
                        .HasForeignKey("maDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.Tour", "Tour")
                        .WithMany("ThamQuans")
                        .HasForeignKey("maTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Tour", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.LoaiHinhDuLich", "LoaiHinhDuLich")
                        .WithMany("Tours")
                        .HasForeignKey("maLoaiHinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHinhDuLich");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.DiaDiem", b =>
                {
                    b.Navigation("ThamQuans");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Doan", b =>
                {
                    b.Navigation("ChiPhis");

                    b.Navigation("ChiTiets");

                    b.Navigation("PhanBos");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Khach", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiChiPhi", b =>
                {
                    b.Navigation("ChiPhis");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiHinhDuLich", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.NhanVien", b =>
                {
                    b.Navigation("PhanBos");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Tour", b =>
                {
                    b.Navigation("Doans");

                    b.Navigation("GiaTours");

                    b.Navigation("ThamQuans");
                });
#pragma warning restore 612, 618
        }
    }
}
