// <auto-generated />
using System;
using DAL_DataAccessLayer.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL_DataAccessLayer.Migrations
{
    [DbContext(typeof(QuanLiTourDbContext))]
    [Migration("20211026093512_updateFK")]
    partial class updateFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiPhi", b =>
                {
                    b.Property<int>("maChiPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<int>("maLoaiCP")
                        .HasColumnType("int");

                    b.Property<decimal>("soTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maChiPhi");

                    b.HasIndex("maDoan");

                    b.HasIndex("maLoaiCP");

                    b.ToTable("ChiPhis");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiTiet", b =>
                {
                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<int>("maKh")
                        .HasColumnType("int");

                    b.HasKey("maDoan", "maKh");

                    b.HasIndex("maKh");

                    b.ToTable("ChiTiets");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.DiaDiem", b =>
                {
                    b.Property<int>("maDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenDiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maDiaDiem");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Doan", b =>
                {
                    b.Property<int>("maDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("doanhThu")
                        .HasColumnType("real");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.HasKey("maDoan");

                    b.ToTable("Doans");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.GiaTour", b =>
                {
                    b.Property<int>("maGiaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("maTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("thanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maGiaTour");

                    b.HasIndex("maTour");

                    b.ToTable("GiaTours");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Khach", b =>
                {
                    b.Property<int>("maKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cnmd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenKh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maKh");

                    b.ToTable("Khachs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiChiPhi", b =>
                {
                    b.Property<int>("maLoaiCP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenLoaiCP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maLoaiCP");

                    b.ToTable("LoaiChiPhis");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiHinhDuLich", b =>
                {
                    b.Property<int>("maLoaiHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenLoaiHinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maLoaiHinh");

                    b.ToTable("LoaiHinhDuLichs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.NhanVien", b =>
                {
                    b.Property<int>("maNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenNv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maNv");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.PhanBo", b =>
                {
                    b.Property<int>("maNv")
                        .HasColumnType("int");

                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<string>("nhiemVu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maNv", "maDoan");

                    b.HasIndex("maDoan");

                    b.ToTable("PhanBos");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ThamQuan", b =>
                {
                    b.Property<int>("maDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("maTour")
                        .HasColumnType("int");

                    b.Property<int>("thuTuThamQuan")
                        .HasColumnType("int");

                    b.HasKey("maDiaDiem", "maTour");

                    b.HasIndex("maTour");

                    b.ToTable("ThamQuans");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Tour", b =>
                {
                    b.Property<int>("maTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("dacDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("khachSan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maDoan")
                        .HasColumnType("int");

                    b.Property<int>("maLoaiHinh")
                        .HasColumnType("int");

                    b.Property<string>("noiDungTour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenTour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maTour");

                    b.HasIndex("maDoan");

                    b.HasIndex("maLoaiHinh");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiPhi", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("ChiPhis")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.LoaiChiPhi", "LoaiChiPhi")
                        .WithMany("ChiPhis")
                        .HasForeignKey("maLoaiCP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("LoaiChiPhi");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ChiTiet", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("ChiTiets")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.Khach", "Khach")
                        .WithMany("ChiTiets")
                        .HasForeignKey("maKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("Khach");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.GiaTour", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Tour", "Tour")
                        .WithMany("GiaTours")
                        .HasForeignKey("maTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.PhanBo", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("PhanBos")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.NhanVien", "NhanVien")
                        .WithMany("PhanBos")
                        .HasForeignKey("maNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.ThamQuan", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.DiaDiem", "DiaDiem")
                        .WithMany("ThamQuans")
                        .HasForeignKey("maDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.Tour", "Tour")
                        .WithMany("ThamQuans")
                        .HasForeignKey("maTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Tour", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Entities.Doan", "Doan")
                        .WithMany("Tours")
                        .HasForeignKey("maDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_DataAccessLayer.Entities.LoaiHinhDuLich", "LoaiHinhDuLich")
                        .WithMany("Tours")
                        .HasForeignKey("maLoaiHinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("LoaiHinhDuLich");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.DiaDiem", b =>
                {
                    b.Navigation("ThamQuans");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Doan", b =>
                {
                    b.Navigation("ChiPhis");

                    b.Navigation("ChiTiets");

                    b.Navigation("PhanBos");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Khach", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiChiPhi", b =>
                {
                    b.Navigation("ChiPhis");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.LoaiHinhDuLich", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.NhanVien", b =>
                {
                    b.Navigation("PhanBos");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Entities.Tour", b =>
                {
                    b.Navigation("GiaTours");

                    b.Navigation("ThamQuans");
                });
#pragma warning restore 612, 618
        }
    }
}
